---
title: "Homework 2"
author: "Qianlang Chen"

# CS 2100
# W 01/29/20

output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section 2.1

## 1. Exercise 11 (p97)

### Part (a)

Let $a, b$ be the two given odd integers. By definition of odd, we have
$$a = 2m + 1, b = 2n+1 : m, n \in \mathbb{Z}$$

By substitution,
$$
\begin{aligned}
  ab &= (2m + 1)(2n + 1) \\
     &= 4mn + 2m + 2n + 1 \\
     &= 2(2mn + m + n) + 1 \\
     &= 2k + 1, \text{ where } k = 2mn + m + n
\end{aligned}
$$

By closure under addition and multiplication, $k \in \mathbb{Z}$. By definition of odd, we have that $ab$ is an odd number.

### Part (b)

Let $a$ be the given odd integer and $b$ be the given even integer. By definition of odd and even, we have
$$a = 2m + 1, b = 2n : m, n \in \mathbb{Z}$$

By substitution,
$$
\begin{aligned}
  ab &= (2m + 1)2n \\
     &= 4mn + 2n \\
     &= 2(2mn + n) \\
     &= 2k, \text{ where } k = 2mn + n
\end{aligned}
$$

By closure under addition and multiplication, $k \in \mathbb {Z}$. By definition of even, we have that $ab$ is an even number.

### Part (c)

Let $a$ be the given even integer and $b$ be the given integer that is divisible by 3.

By definition of even, we have
$$a = 2m : m \in \mathbb{Z}$$

By definition of being divisible by 3, we have
$$b = 3n : n \in \mathbb{Z}$$

By substitution,
$$
\begin{aligned}
  ab &= 2m \cdot 3n \\
     &= 6mn \\
     &= 6k, \text{ where } k = mn
\end{aligned}
$$

By closure under addition and multiplication, $k \in \mathbb {Z}$. By definition of being divisible by 6, we have that $ab$ is divisible by 6.

\pagebreak
## 2. Exercise 12.d (p97)

This pair of statements are *not* contrapositives of one another.

* Counterexample of case (i): a person that likes computers but does not like computer science.

* Counterexample of case (ii): a person that does not like computers but likes computer science.

## 3. Exercise 13.a (p97)

Contrapositive: "if $m = 0$ and $n = 0$, then $m^2 + n^2 = 0$."

Proof of the contrapositive: Since $m = 0$ and $n = 0$, by substitution, we have
$$m^2 + n^2 = 0^2 + 0^2 = 0$$

Since the contrapositive is true, the original statement "if $m^2 + n^2 \neq 0$, then $m \neq 0$ or $n \neq 0$" is true.

## 4. Exercise 14.c (p98)

Let $n$ be a number preceding a perfect cube. Since any perfect cube is in the form of $x^3$ where $x$ is an integer, we have that $n = x^3 - 1$.

The expression $x^3 - 1$ is equivalent to $(x - 1)(x^2 + x + 1)$:
$$
\begin{aligned}
  (x - 1)(x^2 + x + 1) &= x(x^2 + x + 1) - 1(x^2 + x + 1) \\
                       &= (x \cdot x^2 + x \cdot x + x \cdot 1) - (1 \cdot x^2 + 1 \cdot x + 1 \cdot 1) \\
                       &= x^3 + x^2 + x - x^2 - x - 1 \\
                       &= x^3 - 1
\end{aligned}
$$

Now, since $n = x^3 - 1$, $n$ can always be factorized into $(x - 1)$ and $(x^2 + x + 1)$.

* When $x$ is zero or negative, $n$ is negative, which can never be prime.

* When $x$ is 1, $n = 1^3 - 1 = 0$, which is not prime.

* When $x$ is 2, $n = 2^3 - 1 = 7$, which is prime.

* When $x$ is 3 or higher, since $n$ can always be factorized into $(x - 1)$ and $(x^2 + x + 1)$, but $(x - 1)$ is not 1 or n, $n$ is divisible by some other integer that is not 1 or n. Therefore, $n$ is not prime.

* When $x$ is not an integer, $n$ is not an integer, which is not prime.

Since the above cases cover all possibilities of $x$, 7 is indeed the only prime preceding a perfect cube.

\pagebreak
# Section 2.2

## 5. Exercise 7.e (p108)

Let $m$ be the given $10^{n - 1} - 1$ that is divisible by 9. Since $m$ is divisible by 9, $m = 9k : k \in \mathbb{Z}$.

Since $10^n = 10 \cdot 10^{n - 1}$, we have
$$
\begin{aligned}
  10^n - 1 &= 10 \cdot 10^{n - 1} - 1 \\
           &= 10 \cdot (10^{n - 1} - 1 + 1) - 1 \\
           &= 10 \cdot (m + 1) - 1 &\text{Substituting }m = 10^{n - 1} - 1 \\
           &= 10 \cdot (9k + 1) - 1 &\text{Substituting }9k = m \\
           &= 90k + 10 - 1 &\text{Distributing 10} \\
           &= 90k + 9 \\
           &= 9 \cdot (10k + 1) &\text{Factoring out 9} \\
           &= 9c &\text{ Where } c = 10k + 1
\end{aligned}
$$

By closure under addition and multiplication, $c \in \mathbb{Z}$. By definition of being divisible by 9, $10^n - 1$ is divisible by 9.

\pagebreak
## 6. Exercise 16 (p109)

Since $n$ is not divisible by 3, by the division theorem, $n = 3q + r : q, r \in \mathbb{Z}, 0 < r < 3$. In other words, one of the following cases about $r$ must be true:

**Case I,** when r = 1, meaning that n = 3q + 1:

$$
\begin{aligned}
  n^2 + 2 &= (3q + 1)^2 + 2 &\text{Substituting }3q + 1 = n \\
          &= 9q^2 + 6q + 1 + 2 \\
          &= 9q^2 + 6q + 3 \\
          &= 3 \cdot (3q^2 + 2q + 1) &\text{Factoring out 3} \\
          &= 3k &\text{ Where }k = 3q^2 + 2q + 1
\end{aligned}
$$

By closure under addition and multiplication, $k \in \mathbb{Z}$. By definition of being divisible by 3, $n^2 + 2$ is divisible by 3.

**Case II,** when r = 2, meaning that n = 3q + 2:

$$
\begin{aligned}
  n^2 + 2 &= (3q + 2)^2 + 2 &\text{Substituting }3q + 2 = n \\
          &= 9q^2 + 12q + 4 + 2 \\
          &= 9q^2 + 12q + 6 \\
          &= 3 \cdot (3q^2 + 4q + 2) &\text{Factoring out 3} \\
          &= 3k &\text{ Where }k = 3q^2 + 4q + 2
\end{aligned}
$$

By closure under addition and multiplication, $k \in \mathbb{Z}$. By definition of being divisible by 3, $n^2 + 2$ is divisible by 3.

Therefore, $n^2 + 2$ is divisible by 3 in every possible case.

\pagebreak
## 7. Exercise 20 (p109)

Let $n$ be any integer. Let $s = (n - 1)^3 + n^3 + (n + 1)^3$, which is the sum of three consecutive perfect cubes mentioned in the problem. After simplifying the expression of $s$, we have
$$
\begin{aligned}
  s &= (n - 1)^3 + n^3 + (n + 1)^3 \\
    &= (n^3 - 3n^2 + 3n - 1) + n^3 + (n^3 + 3n^2 + 3n + 1) \\
    &= 3n^3 + 6n \\
    &= 3n \cdot (n^2 + 2) &\text{Factoring out }3n
\end{aligned}
$$

Now, one of the following cases about $n$ must be true:

**Case I,** when $n$ is divisible by 3:

Since $n$ is divisible by 3, meaning that $n = 3k : k \in \mathbb{Z}$, we have
$$
\begin{aligned}
  s &= 3n \cdot (n^2 + 2) \\
    &= 3 \cdot 3k \cdot (n^2 + 2) &\text{Substituting }3k = n \\
    &= 9k \cdot (n^2 + 2) \\
    &= 9c &\text{Where }c = k \cdot (n^2 + 2)
\end{aligned}
$$

By closure under addition and multiplication, $c \in \mathbb{Z}$. By definition of being divisible by 9, $s$ is divisible by 9.

**Case II,** when $n$ is not divisible by 3:

Since $n$ is not divisible by 3, according to what is proven by *Exercise 16,* $(n^2 + 2)$ is divisible by 3. This means that $n^2 + 2 = 3k : k \in \mathbb{Z}$, and we have
$$
\begin{aligned}
  s &= 3n \cdot (n^2 + 2) \\
    &= 3n \cdot 3k &\text{Substituting }3k = n^2 + 2 \\
    &= 9nk \\
    &= 9c &\text{Where }c = nk
\end{aligned}
$$

By closure under addition and multiplication, $c \in \mathbb{Z}$. By definition of being divisible by 9, $s$ is divisible by 9.

Therefore, $s$ is divisible by 9 is every possible case.

\pagebreak
## 8. *Show that the square of an integer not divisible by 5 leaves a remainder of 1 or 4 when divided by 5.*

Let $n$ be the given integer that is not divisible by 5. By the division theorem, since $n$ is not divisible by 5, $n = 5q + r : q, r \in \mathbb{Z}, 0 < r < 5$. In other words, one of the following cases about $r$ must be true:

**Case I, ** when r = 1, meaning that $n = 5q + 1$:
$$
\begin{aligned}
  n^2 &= (5q + 1)^2 &\text{Substituting }5q + 1 = n \\
      &= (25q^2 + 10q) + 1 \\
      &= 5 \cdot (5q^2 + 2q) + 1 &\text{Factoring out 5} \\
      &= 5k + 1 &\text{ Where }k = 5q^2 + 2q
\end{aligned}
$$

By closure under addition and multiplication, $k \in \mathbb{Z}$. By the division theorem, $n^2$ leaves a remainder of 1 when divided by 5.

**Case II, ** when r = 2, meaning that $n = 5q + 2$:
$$
\begin{aligned}
  n^2 &= (5q + 2)^2 &\text{Substituting }5q + 2 = n \\
      &= (25q^2 + 20q) + 4 \\
      &= 5 \cdot (5q^2 + 4q) + 4 &\text{Factoring out 5} \\
      &= 5k + 4 &\text{ Where }k = 5q^2 + 4q
\end{aligned}
$$

By closure under addition and multiplication, $k \in \mathbb{Z}$. By the division theorem, $n^2$ leaves a remainder of 4 when divided by 5.

**Case III, ** when r = 3, meaning that $n = 5q + 3$:
$$
\begin{aligned}
  n^2 &= (5q + 3)^2 &\text{Substituting }5q + 3 = n \\
      &= 25q^2 + 30q + 9 \\
      &= (25q^2 + 30q + 5) + 4 \\
      &= 5 \cdot (5q^2 + 6q + 1) + 4 &\text{Factoring out 5} \\
      &= 5k + 4 &\text{ Where }k = 5q^2 + 6q + 1
\end{aligned}
$$

By closure under addition and multiplication, $k \in \mathbb{Z}$. By the division theorem, $n^2$ leaves a remainder of 4 when divided by 5.

**Case IV, ** when r = 4, meaning that $n = 5q + 4$:
$$
\begin{aligned}
  n^2 &= (5q + 4)^2 &\text{Substituting }5q + 4 = n \\
      &= 25q^2 + 40q + 16 \\
      &= (25q^2 + 40q + 15) + 1 \\
      &= 5 \cdot (5q^2 + 8q + 3) + 1 &\text{Factoring out 5} \\
      &= 5k + 1 &\text{ Where }k = 5q^2 + 8q + 3
\end{aligned}
$$

By closure under addition and multiplication, $k \in \mathbb{Z}$. By the division theorem, $n^2$ leaves a remainder of 1 when divided by 5.

Therefore, the $n^2$ leaves a remainder of 1 or 4 when divided by 5 in every possible case.

\pagebreak
## 9. Exercise 26.c (p109)

First, let us prove that a perfect square $k^2$ is divisible by 4 if and only if $k$ is even.

Let $n$ be a perfect square, and by definition, $n = k^2 : k \in \mathbb{Z}$. Since $k$ must be either even or odd, one of the following cases must be true:

**Case I,** when $k$ is even:

Since $k$ is even, $k = 2c : c \in \mathbb{Z}$. By substitution, we have
$$n = k^2 = (2c)^2 = 4c^2 = 4m \text{ where }m = c^2$$

By closure under addition and multiplication, $m \in \mathbb{Z}$. By definition of being divisible by 4, $n$ is divisible by 4.

**Case II,** when $k$ is odd:

Since $k$ is odd, $k = 2c + 1 : c \in \mathbb{Z}$. By substitution, we have
$$
\begin{aligned}
  n = k^2 &= (2c + 1)^2 \\
          &= 4c^2 + 4c + 1 \\
          &= 4 \cdot (c^2 + c) + 1 \\
          &= 4m + 1 \text{ where }m = c^2 + c
\end{aligned}
$$

By closure under addition and multiplication, $m \in \mathbb{Z}$. By the division theorem, $n$ leaves a remainder of 1 when divided by 4, implying that $n$ is not divisible by 4.

Therefore, *every perfect square $k^2$ is divisible by 4 if and only if $k$ is even.*

Now, let us prove the contrapositive of the original problem statement: "for every three integers $a, b$, and $c$ where $c^2 = a^2 + b^2$, if not both $a$ and $b$ are even, then $c$ is not even."

Since every integer is either even or odd, at least one of $\{a, b\}$ must be odd for the above condition to be true. Therefore, we can let $j$ be one of $\{a, b\}$ that is odd and $k$ be the other (which can be either even or odd). Since $j$ is odd, $j = 2p + 1 : p \in \mathbb{Z}$, and this leads us into one of the following:

**Case I,** when $k$ is even:

By definition of even, $k = 2q : q \in \mathbb{Z}$. By substitution, we have
$$
\begin{aligned}
  c^2 &= j^2 + k^2 \\
      &= (2p + 1)^2 + (2q)^2 &\text{Substituting }2p + 1 = j \text{ and }2q = k \\
      &= 4p^2 + 4p + 1 + 4p^2 \\
      &= 4 \cdot (p^2 + p + q^2) + 1 &\text{Factoring out 4} \\
      &= 4m + 1 &\text{ Where }m = p^2 + p + q^2
\end{aligned}
$$

By closure under addition and multiplication, $m \in \mathbb{Z}$. By the division theorem, $c^2$ is not divisible by 4, which means that $c$ is not even, according to what we have proved earlier.


**Case II,** when $k$ is odd:

By definition of odd, $k = 2q + 1 : q \in \mathbb{Z}$. By substitution, we have
$$
\begin{aligned}
  c^2 &= j^2 + k^2 \\
      &= (2p + 1)^2 + (2q + 1)^2 &\text{Substituting }2p + 1 = j \text{ and }2q + 1 = k \\
      &= 4p^2 + 4p + 1 + 4q^2 + 4q + 1 \\
      &= 4p^2 + 4p + 4q^2 + 4q + 2 \\
      &= 4 \cdot (p^2 + p + q^2 + q) + 2 &\text{Factoring out 4} \\
      &= 4m + 2 &\text{ Where }m = p^2 + p + q^2 + q
\end{aligned}
$$

By closure under addition and multiplication, $m \in \mathbb{Z}$. By the division theorem, $c^2$ is not divisible by 4, which means that $c$ is not even, according to what we have proved earlier.

Therefore, $c$ is not even in every possible case. Also, since the contrapositive is true, the original statement is true.

\pagebreak
# Section 2.3

## 10. Exercise 2 (p121)

### Part (a)

* $R(1)$: $a_1 = 2^{1 - 1} + 3 = 4$

* $R(2)$: $a_2 = 2^{2 - 1} + 3 = 5 = 2a_1 - 3$

* $R(3)$: $a_3 = 2^{3 - 1} + 3 = 7 = 2a_2 - 3$

* $R(4)$: $a_4 = 2^{4 - 1} + 3 = 11 = 2a_3 - 3$

According to the above, $R(1), R(2), R(3)$, and $R(4)$ are all true.

### Part (b)

* $R(8)$: $a_8 = 2^{8 - 1} + 3 = 131$

* $R(9)$: $a_9 = 2^{9 - 1} + 3 = 259$

### Part (c)

Since $R(8)$ is verified to be true, meaning that $a_n = a_k$ for $n = k = 8$, we have
$$
\begin{aligned}
  a_{n + 1} &= 2^{(n - 1) + 1} + 3 \\
            &= 2 \cdot 2^{n - 1} + 3 \\
            &= 2 \cdot (2^{n - 1} + 3 - 3) + 3 \\
            &= 2 \cdot (2^{n - 1} + 3) - 6 + 3 \\
            &= 2a_n - 3 \\
            &= 2a_k - 3 \\
            &= a_{k + 1}
\end{aligned}
$$

Since $a_{n + 1} = a_{k + 1}$ and $n + 1 = k + 1 = 9$, $R(9)$ is now verified to be true.

\pagebreak
## 11. Exercise 3.f (p121)

**Statement:** show that $a_n = a_k$, where $a_n = 2^{n - 1} + 3$ and $a_k = 2a_{k - 1} - 3$.

**Base case:** when $n = k = 1$, $a_n = 2^{1 - 1} + 3 = 4 = a_k$.

**Induction hypothesis:** assume that $a_n = a_k$ when $n = k = m$, $m \in \mathbb{Z} : m \ge 1$.

**Induction step:** when $n = k = m + 1$,
$$
\begin{aligned}
  a_n &= 2^{(m + 1) - 1} + 3 \\
      &= 2 \cdot 2^{m - 1} + 3 \\
      &= 2 \cdot (2^{m - 1} + 3 - 3) + 3 \\
      &= 2 \cdot (2^{m - 1} + 3) - 6 + 3 \\
      &= 2a_m - 3 \\
      &= a_{m + 1} \\
      &= a_k
\end{aligned}
$$

Verifying the first four terms:

* $a_1 = 2^{1 - 1} + 3 = 4$

* $a_2 = 2^{2 - 1} + 3 = 5 = 2a_1 - 3$

* $a_3 = 2^{3 - 1} + 3 = 7 = 2a_2 - 3$

* $a_4 = 2^{4 - 1} + 3 = 11 = 2a_3 - 3$

## 12. Exercise 4.e (p122)

**Statement:** show that $b_n = b_k$, where $b_n = 3 \cdot 2^n - n - 2$ and $b_k = 2b_{k - 1} + k$.

**Base case:** when $n = k = 1$, $b_n = 3 \cdot 2^1 - 1 - 2 = 3 = b_k$.

**Induction hypothesis:** assume that $a_n = a_k$ when $n = k = m - 1$, $m \in \mathbb{Z} : m > 1$.

**Induction step:** when $n = k = m$,
$$
\begin{aligned}
  a_n &= 3 \cdot 2^m - m - 2 \\
      &= 3 \cdot (2 \cdot 2^{m - 1}) - m + m - m - 2 \\
      &= 2 \cdot (3 \cdot 2^{m - 1}) - 2m - 2 + m \\
      &= 2 \cdot (3 \cdot 2^{m - 1} - m - 1) + m \\
      &= 2 \cdot (3 \cdot 2^{m - 1} - m + 1 - 1 - 1) + m \\
      &= 2 \cdot (3 \cdot 2^{m - 1} - (m - 1) - 2) + m \\
      &= 2a_{m - 1} + m \\
      &= 2a_{k - 1} + k \\
      &= a_k
\end{aligned}
$$

\pagebreak
## 13. Exercise 8.f (p122)

**Statement:** show that $a_n = b_n$, where $a_n = \sum_{i = 1}^n \frac{1}{i(i + 1)}$ and $b_n = \frac{n}{n + 1}$.

**Base case:**
$$
\begin{aligned}
  a_1 &= \sum_{i = 1}^1 \frac{1}{i(i + 1)} = \frac{1}{1(1 + 1)} = \frac{1}{2} \\
      &= \frac{1}{1 + 1} = b_1
\end{aligned}
$$

**Induction hypothesis:** assume that $a_{k - 1} = b_{k - 1}$, $k \in \mathbb{Z} : k > 1$.

**Induction step:**
$$
\begin{aligned}
  a_k &= \sum_{i = 1}^k \frac{1}{i(i + 1)} \\
      &= (\sum_{i = 1}^{k - 1} \frac{1}{i(i + 1)}) + \frac{1}{k(k + 1)} \\
      &= a_{k - 1} + \frac{1}{k(k + 1)} \\
      &= b_{k - 1} + \frac{1}{k(k + 1)} \\
      &= \frac{k - 1}{(k - 1) + 1} + \frac{1}{k(k + 1)} \\
      &= \frac{(k - 1)(k + 1)}{k(k + 1)} + \frac{1}{k(k + 1)} \\
      &= \frac{k^2 - 1 + 1}{k(k + 1)} \\
      &= \frac{k}{k + 1} \\
      &= b_k
\end{aligned}
$$

Verifying the first four terms:

$$
\begin{aligned}
  a_1 &= \sum_{i = 1}^1 \frac{1}{i(i + 1)} = \frac{1}{2} = \frac{1}{1 + 1} = b_1; \\
  a_2 &= \sum_{i = 1}^2 \frac{1}{i(i + 1)} = \frac{1}{2} + \frac{1}{6} = \frac{1}{3} = \frac{1}{2 + 1} = b_2; \\
  a_3 &= \sum_{i = 1}^2 \frac{1}{i(i + 1)} = \frac{1}{3} + \frac{1}{12} = \frac{1}{4} = \frac{1}{3 + 1} = b_3; \\
  a_4 &= \sum_{i = 1}^2 \frac{1}{i(i + 1)} = \frac{1}{4} + \frac{1}{20} = \frac{1}{5} = \frac{1}{4 + 1} = b_4; \\
\end{aligned}
$$

\pagebreak
## 14. Exercise 13 (p122)

**Statement:** show that $a_n = b_n$, where
$$
\begin{aligned}
&a_n = \sum_{i = 0}^n x^i, \\
&b_n = \frac{x^{n + 1} - 1}{x - 1}, \\
&x \in \mathbb{R} : x \neq 1
\end{aligned}
$$

**Base case:**
$$
\begin{aligned}
  a_0 &= \sum_{i = 0}^0 x^i = x^0 = 1 \\
      &= \frac{x - 1}{x - 1} = \frac{x^{0 + 1} - 1}{x - 1} = b_0
\end{aligned}
$$

**Induction hypothesis:** assume that $a_{k - 1} = b_{k - 1}$, $k \in \mathbb{Z} : k > 0$.

**Induction step:**
$$
\begin{aligned}
  a_k &= \sum_{i = 0}^k x^i \\
      &= (\sum_{i = 0}^{k - 1} x^i) + x^k \\
      &= a_{k - 1} + x^k \\
      &= b_{k - 1} + x^k \\
      &= \frac{x^{(k - 1) + 1} - 1}{x - 1} + x^k \\
      &= \frac{x^k - 1}{x - 1} + \frac{x^k(x - 1)}{x - 1} \\
      &= \frac{x^k - 1 + x^k \cdot x - x^k}{x - 1} \\
      &= \frac{x^{k + 1} - 1}{x - 1} \\
      &= b_k
\end{aligned}
$$

\pagebreak
# Section 2.4

## 15. Exercise 1.d (p130)

$$d_n = d_{n - 1} + \frac{1}{(2n - 1)(2n + 1)}, d_1 = \frac{1}{3}$$

## 16. Exercise 2.d (p130)

**Statement:** show that $a_n = d_n$, where $a_n = a_{n - 1} + \frac{1}{(2n - 1)(2n + 1)}, a_1 = \frac{1}{3}$, and $d_n = \frac{n}{2n + 1}$.

**Base case:**
$$a_1 = \frac{1}{3} = \frac{1}{2 \cdot 1 + 1} = d_1$$

**Induction hypothesis:** assume that $a_{k - 1} = d_{k - 1}$, $k \in \mathbb{Z} : k > 1$.

**Induction step:**
$$
\begin{aligned}
  a_k &= a_{k - 1} + \frac{1}{(2k - 1)(2k + 1)} \\
      &= d_{k - 1} + \frac{1}{(2k - 1)(2k + 1)} \\
      &= \frac{k - 1}{2(k - 1) + 1} + \frac{1}{(2k - 1)(2k + 1)} \\
      &= \frac{k - 1}{2k - 1} + \frac{1}{(2k - 1)(2k + 1)} \\
      &= \frac{(k - 1)(2k + 1) + 1}{(2k - 1)(2k + 1)} \\
      &= \frac{2k^2 + k - 2k - 1 + 1}{(2k - 1)(2k + 1)} \\
      &= \frac{2k^2 - k}{(2k - 1)(2k + 1)} \\
      &= \frac{k(2k - 1)}{(2k - 1)(2k + 1)} \\
      &= \frac{k}{2k + 1} \\
      &= d_k
\end{aligned}
$$

\pagebreak
## 17. Exercise 4.b (p130)

**Statement:** let $D(n)$ be the statement "$n^3 - n$ is divisible by 3." Show that $D(n)$ is true for each integer $n$, where $n \ge 1$.

**Base Case:** when $n = 1$, $D(n)$ states that $1^3 - 1 = 0$ is divisible by 3, which is true.

**Induction hypothesis:** assume that $D(n)$ is true for $n = k - 1$, $k \in \mathbb{Z} : k > 1$.

**Induction step:** since $D(k - 1)$ is true, meaning that $(k - 1)^3 - (k - 1)$ is divisible by 3, we have $(k - 1)^3 - (k - 1) = 3q : q \in \mathbb{Z}$, by definition of being divisible by 3.

Now, to show that $D(k)$ is true, we have
$$
\begin{aligned}
  k^3 - k &= (k^3 - 3k^2 + 2k) + 3k^2 - 3k \\
          &= (k^3 - 3k^2 - 3k - 1) - (k - 1) + 3k^2 - 3k \\
          &= (k - 1)^3 - (k - 1) + 3k^2 - 3k \\
          &= 3q + 3k^2 - 3k &\text{Substituting }3q = (k - 1)^3 - (k - 1) \\
          &= 3(q + k^2 - k)\\
          &= 3c &\text{Where }c = q + k^2 - k
\end{aligned}
$$

By closure under addition and multiplication, $c \in \mathbb{Z}$. By definition of being divisible by 3, $k^3 - k$ is divisible by 3, meaning that $D(k)$ is true.

## 18. Exercise 6 (p131)

**Statement:** let $D(n)$ be the statement "$2^{3n} - 1$ is divisible by 7." Show that $D(n)$ is true for each integer $n$, where $n \ge 2$.

**Base Case:** when $n = 2$, $D(n)$ states that $2^{3 \cdot 2} - 1 = 63 = 7 \cdot 9$ is divisible by 7, which is true.

**Induction hypothesis:** assume that $D(n)$ is true for $n = k - 1$, $k \in \mathbb{Z} : k > 1$.

**Induction step:** since $D(k - 1)$ is true, meaning that $2^{3(k - 1)} - 1$ is divisible by 7, we have $2^{3(k - 1)} - 1 = 7q : q \in \mathbb{Z}$, by definition of being divisible by 7.

Now, to show that $D(k)$ is true, we have
$$
\begin{aligned}
  2^{3k} - 1 &= 2^3 \cdot 2^{3(k - 1)} - 1 \\
             &= 8 \cdot 2^{3(k - 1)} - 8 + 7 \\
             &= 8 \cdot (2^{3(k - 1)} - 1) + 7 \\
             &= 8 \cdot 7q + 7 &\text{Substituting }7q = 2^{3(k - 1)} - 1 \\
             &= 7 \cdot (8q + 1) \\
             &= 7c &\text{Where }c = 8q + 1
\end{aligned}
$$

By closure under addition and multiplication, $c \in \mathbb{Z}$. By definition of being divisible by 7, $2^{3k} - 1$ is divisible by 7, meaning that $D(k)$ is true. Now, since $2^{3n} - 1 > 7$ when $n \ge 2$, but $2^{3n} - 1$ is divisible by 7, $2^{3n} - 1$ is not prime for all $n \ge 2$.

\pagebreak
# Section 2.5

## 19. Exercise 12 (p147)



## 20. Exercise 20 (p148)



## 21. Exercise 32.b (p149)



## 22. Exercise 34.b (p149)




























