---
title: "Homework 2"
author: "Qianlang Chen"

# CS 3130
# M 02/03/20

output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

## Part (a)

Rolling a six-sided die leaves us with the following sample space for the outcomes:
$$\Omega = \{1, 2, 3, 4, 5, 6\}$$

Also, according to the problem description, we have
$$
\begin{aligned}
         A &= \{1, 2, 3, 4\}; \\
         B &= \{2, 4, 6\}; \\
  A \cap B &= \{2, 4\}
\end{aligned}
$$

Since these outcomes are equally likely to happen,
$$P(A \cap B) = \frac{|A \cap B|}{|\Omega|} = \frac{2}{6} = \frac{1}{3}$$

However,
$$P(A) \times P(B) = \frac{|A|}{|\Omega|} \times \frac{|B|}{|\Omega|} = \frac{4}{6} \times \frac{3}{6} = \frac{1}{3} = P(A \cap B)$$

Therefore, by definition of independence, the events $A$ and $B$ are independent.

## Part (b)

Flipping two fair coins leaves us with the following sample space for the outcomes:
$$\Omega = \{(H, H), (H, T), (T, H), (T, T)\}$$

Also, according to the problem description, we have
$$
\begin{aligned}
         A &= \{(H, H), (T, T)\}; \\
         B &= \{(H, T), (T, H), (T, T)\}; \\
  A \cap B &= \{(T, T)\}
\end{aligned}
$$

Since these outcomes are equally likely to happen,
$$P(A \cap B) = \frac{|A \cap B|}{|\Omega|} = \frac{1}{4}$$

However,
$$P(A) \times P(B) = \frac{|A|}{|\Omega|} \times \frac{|B|}{|\Omega|} = \frac{2}{4} \times \frac{3}{4} = \frac{3}{8} \ne P(A \cap B)$$

Therefore, by definition of independence, the events $A$ and $B$ are not independent.

\pagebreak
# Problem 2

Let $D$ be the event that the patient has heart disease and $T$ be the event that the test turns out positive. According to the problem statement, we have
$$
\begin{aligned}
        P(D) &= \frac{1}{5}; \\
  P(T | D^c) &= \frac{1}{10}; \\
    P(T | D) &= \frac{9}{10}
\end{aligned}
$$

By the Law of Total Probability, we have
$$
\begin{aligned}
  P(T) &= P(T | D) \times P(D) + P(T | D^c) \times P(D^c) \\
       &= \frac{9}{10} \times \frac{1}{5} + \frac{1}{10} \times (1 - \frac{1}{5}) \\
       &= \frac{13}{50}
\end{aligned}
$$

By Bayes' Rule, we have
$$
\begin{aligned}
  P(D | T) &= P(T | D) \times \frac{P(D)}{P(T)} \\
           &= \frac{9}{10} \times \frac{1}{5} \div \frac{13}{50} \\
           &= \boxed{\frac{9}{13}}
\end{aligned}
$$

\pagebreak
# Problem 3

## Part (a)

Since $A$ and $B$ are independent events, by definition, $P(A) = P(A | B)$ and also $P(A \cap B) = P(A) \times P(B)$.

Now, according to the Probability Rules, we have
$$
\begin{aligned}
  P(A \cup B) &= P(A) + P(B) - P(A \cap B) \\
              &= P(A) + P(B) - P(A) \times P(B) \\
              &= P(A | B) + P(B) - P(A | B) \times P(B) \\
              &= \frac{1}{2} + x - \frac{1}{2}x \\
              &= \boxed{\frac{1 + x}{2}}
\end{aligned}
$$

## Part (b)

First of all, since $B \subseteq (A \cup B)$, we have $B \cap (A \cup B) = B$.

Now, we have,
$$
\begin{aligned}
  P(B | A \cup B) &= \frac{P(B \cap (A \cup B))}{P(A \cup B)} \\
                  &= \frac{P(B)}{P(A \cup B)}
\end{aligned}
$$

By rearranging, we have
$$
\begin{aligned}
        P(B) &= P(B|A \cup B) \times P(A \cup B) \\
           x &= \frac{2}{3} \times \frac{1 + x}{2} \\
  \implies x &= \boxed{\frac{1}{2}}
\end{aligned}
$$

\pagebreak
# Problem 4
<!--
  3.18 Suppose A and B are events with 0 < P(A) < 1 and 0 < P(B) < 1.
    a. If A and B are disjoint, can they be independent?
    b. If A and B are independent, can they be disjoint?
    c. If A ⊂ B, can A and B be independent?
    d. If A and B are independent, can A and A ∪ B be independent?
-->

## Part (a)

By definition of independence, $P(A \cap B) = P(A) \times P(B)$ if $A$ and $B$ are independent events. Since $A$ and $B$ are disjoint, $P(A \cap B) = 0$. However, the problem states that $P(A) \ne 0$ and $P(B) \ne 0$. Therefore, $A$ and $B$ cannot be disjoint and independent at the same time.

## Part (b)

Same logic as *Part (a)*, two events $A$ and $B$ cannot be disjoint and independent at the same time given that $P(A) \ne 0$ and $P(B) \ne 0$.

## Part (c)

Since $A \subset B$, $P(A \cap B) = P(A)$. If $A$ and $B$ are independent, it would mean that $P(A \cap B) = P(A) \times P(B) = P(A) \times 1$, but the problem states that $P(B) \ne 1$. Therefore, if $A \subset B$, $A$ and $B$ cannot be independent.

## Part (d)

Let events $A$ and $A \cup B$ be independent. By definition of independence, we have $P(A | (A \cup B)^c) = P(A)$.

However, we also have
$$
\begin{aligned}
  P(A | (A \cup B)^c) &= \frac{P(A \cap (A \cup B)^c)}{P((A \cup B)^c)} \\
                      &= \frac{P(A \cap A^c \cap B^c)}{P((A \cup B)^c)} \\
                      &= \frac{0}{P((A \cup B)^c)} \\
                      &= 0
\end{aligned}
$$

This implies $P(A) = 0$, but the problem states that $P(A) \ne 0$. Therefore, the events $A$ and $A \cup B$ cannot be independent.

\pagebreak
# Problem 5

## Part (a)

First, given how the events $A, B$, and $C$ are defined, we have
$$A \cap B \cap C = \{1\}$$

Since all 8 outcomes from the sample space is equally likely,
$$P(A) \times P(B) \times P(C) = \frac{4}{8} \times \frac{4}{8} \times \frac{4}{8} = \frac{1}{8} = P(A \cap B \cap C)$$

## Part (b)

$$P(A) \times P(C) = \frac{4}{8} \times \frac{4}{8} = \frac{1}{4}$$

However,
$$P(A \cap C) = \frac{|\{1\}|}{|\Omega|} = \frac{1}{8} \ne P(A) \times P(C)$$

Therefore, by definition of independence, the events $A$ and $C$ are not independent.

