
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'*Q\xa7\xdb\x12q\xd5v"\x07\x98\xb5\x9d\x82i\xb0'
    
_lr_action_items = {'NAME':([0,4,5,6,8,9,10,11,12,],[2,14,14,14,14,14,14,14,14,]),'MINUS':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[4,-11,10,4,4,4,-10,4,4,4,4,4,-7,-11,-8,10,10,-3,-4,-5,-6,-9,]),'SUCC':([0,4,5,6,8,9,10,11,12,],[5,5,5,5,5,5,5,5,5,]),'LPAREN':([0,4,5,6,8,9,10,11,12,],[6,6,6,6,6,6,6,6,6,]),'NUMBER':([0,4,5,6,8,9,10,11,12,],[7,7,7,7,7,7,7,7,7,]),'$end':([1,2,3,7,13,14,15,17,18,19,20,21,22,],[0,-11,-2,-10,-7,-11,-8,-1,-3,-4,-5,-6,-9,]),'EQUALS':([2,],[8,]),'PLUS':([2,3,7,13,14,15,16,17,18,19,20,21,22,],[-11,9,-10,-7,-11,-8,9,9,-3,-4,-5,-6,-9,]),'TIMES':([2,3,7,13,14,15,16,17,18,19,20,21,22,],[-11,11,-10,-7,-11,-8,11,11,11,11,-5,-6,-9,]),'DIVIDE':([2,3,7,13,14,15,16,17,18,19,20,21,22,],[-11,12,-10,-7,-11,-8,12,12,12,12,-5,-6,-9,]),'RPAREN':([7,13,14,15,16,18,19,20,21,22,],[-10,-7,-11,-8,22,-3,-4,-5,-6,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,4,5,6,8,9,10,11,12,],[3,13,15,16,17,18,19,20,21,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','<ipython-input-7-f49b12234fbe>',54),
  ('statement -> expression','statement',1,'p_statement_expr','<ipython-input-7-f49b12234fbe>',58),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','<ipython-input-7-f49b12234fbe>',62),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','<ipython-input-7-f49b12234fbe>',63),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','<ipython-input-7-f49b12234fbe>',64),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','<ipython-input-7-f49b12234fbe>',65),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','<ipython-input-7-f49b12234fbe>',72),
  ('expression -> SUCC expression','expression',2,'p_expression_succ','<ipython-input-7-f49b12234fbe>',79),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','<ipython-input-7-f49b12234fbe>',84),
  ('expression -> NUMBER','expression',1,'p_expression_number','<ipython-input-7-f49b12234fbe>',88),
  ('expression -> NAME','expression',1,'p_expression_name','<ipython-input-7-f49b12234fbe>',92),
]
