---
title: "Homework 3"
author: "Qianlang Chen"

# CS 2100
# W 02/12/20

output: pdf_document

header-includes:
- \usepackage{venndiagram} # for quickly drawing venn diagrams
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section 3.1 (p193)

## 1. Exercise 2

### Part (a)

4, 8, 12, 16, 20.

### Part (c)

4, 8, 12, 16, 20.

## 2. Exercise 16

### Part (b)

\begin{align*}
  \begin{venndiagram2sets}[labelNotAB = U]
    \fillNotAorB
  \end{venndiagram2sets} \\
  \text{The Left-hand side: }(A \cup B)'
\end{align*}

\begin{align*}
  \begin{venndiagram2sets}[labelNotAB = U]
    \fillNotAorB
  \end{venndiagram2sets} \\
  \text{The Right-hand side: }A' \cap B'
\end{align*}

Therefore, since the Venn diagrams for both sides are the same, $(A \cup B)' = A' \cap B'$.

### Part (d)

\begin{align*}
  \begin{venndiagram2sets}[labelNotAB = U]
    \fillA
  \end{venndiagram2sets} \\
  \text{The Left-hand side: }A \cap (A \cup B)
\end{align*}

\begin{align*}
  \begin{venndiagram2sets}[labelNotAB = U]
    \fillA
  \end{venndiagram2sets} \\
  \text{The Right-hand side: }A
\end{align*}

Therefore, since the Venn diagrams for both sides are the same, $A \cap (A \cup B) = A$.

\pagebreak
## 3. Exercise 17

### Part (b)

\begin{align*}
  \begin{venndiagram3sets}[labelNotABC = U]
    \fillBNotA
    \fillCNotA
  \end{venndiagram3sets} \\
  \text{The Left-hand side: }(B \cup C) - A
\end{align*}

\begin{align*}
  \begin{venndiagram3sets}[labelNotABC = U]
    \fillBNotA
    \fillCNotA
  \end{venndiagram3sets} \\
  \text{The Right-hand side: }(B - A) \cup (C - A)
\end{align*}

Therefore, since the Venn diagrams for both sides are the same, $(B \cup C) - A = (B - A) \cup (C - A)$.

### Part (d)

\begin{align*}
  \begin{venndiagram3sets}[labelNotABC = U]
    \fillANotB
    \fillBNotC
  \end{venndiagram3sets} \\
  \text{The Left-hand side: }(A - B) \cup (B - C)
\end{align*}

\begin{align*}
  \begin{venndiagram3sets}[labelNotABC = U]
    \fillANotC
  \end{venndiagram3sets} \\
  \text{The Right-hand side: }A - C
\end{align*}

As seen from the Venn diagrams, there are some areas covered by the left-hand side but not the right-hand side. Specifically, these are the mentioned areas:

\begin{align*}
  \begin{venndiagram3sets}[labelNotABC = U]
    \fillACapCNotB
    \fillOnlyB
  \end{venndiagram3sets}
\end{align*}

Therefore, the left-hand side may not be a subset of the right-hand side. $(A - B) \cup (B - C) \nsubseteq A - C$. As an example, if
$$
\begin{aligned}
  A &= \{1, 2, 3\}, \\
  B &= \{4, 5, 6\}, \\
  C &= \{7, 8, 9\}, \\
\end{aligned}
$$

then
$$
\begin{aligned}
  (A - B) \cup (B - C) &= \{1, 2, 3, 4, 5, 6\}, \\
                 A - C &= \{1, 2, 3\}; \\
                 \{1, 2, 3, 4, 5, 6\} &\nsubseteq \{1, 2, 3\}
\end{aligned}
$$

## 4. Exercise 18

### Part (b)

$$A - B = \{k : k \in \mathbb{Z}, k \bmod 6 \neq 0\}$$

### Part (e)

$$\mathbb{Z} - A = \{2k + 1 : k \in \mathbb{Z}\}$$

\pagebreak
# Section 3.2 (p208)

## 5. Exercise 1

### Part (b)

$$
\begin{aligned}
  (A \times B) - (A \times A) &= \{2, 4\} \times \{1, 2, 8\} - \{2, 4\} \times \{2, 4\} \\
                              &= \{(2, 1), (2, 2), (2, 8), (4, 1), (4, 2), (4, 8)\} - \{(2, 2), (2, 4), (4, 2), (4, 4)\} \\
                              &= \boxed{\{(2, 1), (2, 8), (4, 1), (4, 8)\}}
\end{aligned}
$$

### Part (d)

$$
\begin{aligned}
  \wp(B \cap C) &= \wp(\{1, 2, 8\} \cap \{1, 2, 5, 6, 10\}) \\
                &= \wp(\{1, 2\}) \\
                &= \boxed{\{\ \{\}, \{1\}, \{2\}, \{1, 2\}\ \}}
\end{aligned}
$$

## 6. Exercise 9

According to the division theorem, every integer falls into one of the following categories:

* $4q$,

* $4q + 1$,

* $4q + 2$,

* $4q + 3$,

where $q \in \mathbb{Z}$. In other words, $\mathbb{Z} = B \cup C \cup S \cup T$, where

* $B = \{4q + 1 : q \in \mathbb{Z}\}$ (given by the problem statement),

* $C = \{4q + 3 : q \in \mathbb{Z}\}$ (given by the problem statement),

* $S = \{4q : q \in \mathbb{Z}\}$,

* $T = \{4q + 2 : q \in \mathbb{Z}\}$.

Also, to show that $A = \{2k : k \in \mathbb{Z}\} = S \cup T$, since every integer is either even or odd,

* when k is even, $2k = 2(2q) = 4q$, where $q$ is an integer by definition of even;

* when k is odd, $2k = 2(2q + 1) = 4q + 2$, where $q$ is an integer by definition of odd.

Therefore, we showed that $A = S \cup T$. Now, we have $\mathbb{Z} = B \cup C \cup S \cup T = A \cup B \cup C$.

According to the definition of a partition, and

* $A \ne B \ne C \ne \emptyset$,

* $A \cap B = A \cap C = B \cap C = \emptyset$,

* $A \cup B \cup C = \mathbb{Z}$,

$\{A, B, C\}$ is a partition of $\mathbb{Z}$.


## 7. Exercise 11

### Part (a)

True.

### Part (b)

False. One counter-example: if $A = \{1\}$ and $B = \{2\}$,
$$
\begin{aligned}
  (A \cup B) \times (A - B) &= \{1, 2\} \times \{1\} \\
                            &= \{(1, 1), (2, 1)\}; \\
                  A^2 - B^2 &= \{(1, 1)\} - \{(2, 2)\} \\
                            &= \{(1, 1)\}; \\
  (A \cup B) \times (A - B) &\ne A^2 - B^2
\end{aligned}
$$


### Part (c)

False. One counter-example: if $A = \{1\}, B = \{2\}$ and $C = \{3\}$,
$$
\begin{aligned}
  A \times (B \times C) &= \{1\} \times (\{2\} \times \{3\}) \\
                        &= \{1\} \times \{(2, 3)\} \\
                        &= \{(1, (2, 3))\}; \\
  (A \times B) \times C &= (\{1\} \times \{2\}) \times \{3\} \\
                        &= \{(1, 2)\} \times \{3\} \\
                        &= \{((1, 2), 3)\}; \\
  A \times (B \times C) &\ne (A \times B) \times C
\end{aligned}
$$

## 8. Exercise 22

According to *Theorem 1*, $|A \times B| = |A| \  |B|$. Therefore,
$$
\begin{aligned}
  |S_1 \times S_2 \times \cdots \times S_{k-1} \times S_k|
  &= |S_1| \  |S_2| \  \cdots \  |S_{k-1}| \  |S_k| \\
  &= (|S_1| \  |S_2| \  \cdots \  |S_{k-1}|) \  |S_k| \\
  &= |S_1 \times S_2 \times \cdots \times S_{k-1}| \  |S_k| \\
  &= \boxed{|(S_1 \times S_2 \times \cdots \times S_{k-1}) \times S_k|}
\end{aligned}
$$

\pagebreak
# Section 3.3 (p219)

## 9. Exercise 2.e

Let an element $x : x \in (\{2n + 1 : n \in \mathbb{Z}\} \cap \{5m + 4 : m \in \mathbb{Z}\})$ be given. By definition of set union, we have that $\exists n \in \mathbb{Z} : x = 2n + 1$ and that $\exists m \in \mathbb{Z} : x = 5m + 4$. Since every integer is either even or odd, one of the following cases about $m$ must be true:

**Case I,** when $m$ is even: by definition of even, $\exists k \in \mathbb{Z} : 2k = m$. By substitution, $x = 5m + 4 = 5 \cdot (2k) + 4 = 10k + 4 = 2 \cdot (5k + 2) = 2c$ for some $c$. Since $x$ has to be in the form of $2n + 1$, this is not a possibility for $x$.

**Case II,** when $m$ is odd: by definition of odd, $\exists k \in \mathbb{Z} : 2k + 1 = m$. By substitution, $x = 5m + 4 = 5 \cdot (2k + 1) + 4 = 10k + 9 = 2 \cdot (5k + 4) + 1 = 2c + 1$ for some $c$. By closure under addition, $c \in \mathbb{Z}$. Since this fits the definition of $x$ and $x$ can be written in the form of $10k + 9$, by definition of a subset, $(\{2n + 1 : n \in \mathbb{Z}\} \cap \{5m + 4 : m \in \mathbb{Z}\}) \subseteq \{10k + 9 : k \in \mathbb{Z}\}$.

## 10. Exercise 3.b

Let an element $x : x \in (\{n^2 - 1 : n \in \mathbb{Z}\} \cap \{2k : k \in \mathbb{Z}\})$ be given. By definition of set union, we have that $\exists n \in \mathbb{Z} : x = n^2 - 1$ and that $\exists k \in \mathbb{Z} : k = 2k$. Since every integer is either even or odd, one of the following cases about $n$ must be true:

**Case I,** when $n$ is even: by definition of even, $\exists m \in \mathbb{Z} : 2m = n$. By substitution, $x = n^2 - 1 = (2m)^2 - 1 = 4m^2 - 1 = 2 \cdot (2m^2 - 1) + 1 = 2c + 1$ for some $c$. Since $x$ has to be in the form of $2k$, this is not a possibility for $x$.

**Case II,** when $n$ is odd: by definition of odd, $\exists m \in \mathbb{Z} : 2m + 1 = n$. By substitution, $x = n^2 - 1 = (2m + 1)^2 - 1 = 4m^2 + 4m + 1 - 1 = 2 \cdot (2m^2 + 2m) = 2c$ for some $c$, and by closure under addition, $c \in \mathbb{Z}$. Also, $4m^2 + 4m = 4(m^2 + m) = 4d$ for some $d$, and by closure under addition, $d \in \mathbb{Z}$. Since this fits the definition of $x$ and $x$ can be written in the form of $4m$, by definition of a subset, $(\{n^2 - 1 : n \in \mathbb{Z}\} \cap \{2k : k \in \mathbb{Z}\}) \subseteq \{4m : m \in \mathbb{Z}\}$.

## 11. Exercise 11.d

First, we have that $C \subseteq (A \cup C)$ because $C \subseteq C$ already.

Now, let us show that $(A \cup C) \subseteq C$.

Let an element $x : x \in (A \cup C)$ be given. By definition of set union, one of the following cases about $x$ must be true:

**Case I,** when $x \in A$: since $A \cup B = B$, we have that $x \in B$. Since $B \cup C = C$, we have that $x \in C$.

**Case II,** when $x \in C$ already.

Therefore, $x \in C$ in every possible case. By definition of a subset, $(A \cup C) \subseteq C$.

Finally, since $C \subseteq (A \cup C)$ and $(A \cup C) \subseteq C$, we have that $(A \cup C) = C$.

## 12. Exercise 13.c

First, let us show that $(A \cup (B - A)) \subseteq B$. Let an element $x : x \in (A \cup (B - A))$ be given. By definition of set union, one of the following cases about $x$ must be true:

**Case I,** when $x \in A$: since $A \subseteq B$, $x \in B$.

**Case II,** when $x \in (B - A)$: by definition of set difference, we have that $x \in B$.

Therefore, $x \in B$ in every possible case. By definition of a subset, $(A \cup (B - A)) \subseteq B$.

Now, to show that $B \subseteq (A \cup (B - A))$, let an element $x : x \in B$ be given. Since $A \subseteq B$, one of the following cases about $x$ must be true:

**Case I,** when $x \in A$ already, meaning that $x \in (A \cup (B - A))$.

**Case II,** when $x \in B$ but $x \notin A$: by definition of set difference, $x \in (B - A)$, also meaning that $x \in (A \cup (B - A))$.

Therefore, $x \in (A \cup (B - A))$ in every possible case. By definition of a subset, $B \subseteq (A \cup (B - A))$.

Finally, since $(A \cup (B - A)) \subseteq B$ and $x \in (A \cup (B - A))$, we have that $(A \cup (B - A)) = B$.

## 13. Exercises 14.e and 15.e

### Exercise 14.e

$$
\begin{aligned}
  (A \cup B) \cap (A' \cap C)' &= (A \cup B) \cap (A \cup C') &\text{De Morgan's} \\
                               &= A \cup (B \cap C')          &\text{Inverse Distributive}
\end{aligned}
$$

### Exercise 15.e

$$(A \cap B) \cup (A' \cup C)' = (A \cap (B \cup C'))$$

## 14. Exercise 19.b

$$
\begin{aligned}
  A \cup (B \cap A') &= (A \cup B) \cap (A \cup A') &\text{Distributive} \\
                     &= B \cap (A \cup A')          &\text{Substituting }B = A \cup B \\
                     &= B \cap U                    &\text{Negation} \\
                     &= B                           &\text{Identity}
\end{aligned}
$$

## 15. Exercies 22.a

First, let us show that $(A \cup B) \times C \subseteq (A \times C) \cup (B \times C)$.

Let a tuple $(x, c) \in (A \cup B) \times C$ be given. By definition of a Cartisian Product and set union, one of the following cases about $x$ must be true:

**Case I,** when $x \in A$, meaning that $(x, c) \in (A \times C)$. This also means that $(x, c) \in (A \times C) \cup (B \times C)$.

**Case II,** when $x \in B$, meaning that $(x, c) \in (B \times C)$. This also means that $(x, c) \in (A \times C) \cup (B \times C)$.

Therefore, $(x, c) \in (A \times C) \cup (B \times C)$ in every possible case. By definition of a subset, $(A \cup B) \times C \subseteq (A \times C) \cup (B \times C)$.

Next, let us show that $(A \times C) \cup (B \times C) \subseteq (A \cup B) \times C$.

Let a tuple $(x, c) \in (A \times C) \cup (B \times C)$ be given. By definition of a Cartisian Produt and set union, one of the following cases about $x$ must be true:

**Case I,** when $(x, c) \in (A \times C)$, meaning that $x \in A$.

**Case II,** when $(x, c) \in (B \times C)$, meaning that $x \in B$.

Therefore, $x \in A$ or $x \in B$ in every possible case, and by definition of set union, we have that $x \in (A \cup B)$, meaning that $(x, c) \in (A \cup B) \times C$. Also, by definition of a subset, $(A \times C) \cup (B \times C) \subseteq (A \cup B) \times C$.

Finally, since $(A \cup B) \times C \subseteq (A \times C) \cup (B \times C)$ and $(A \times C) \cup (B \times C) \subseteq (A \cup B) \times C$, we have that $(A \cup B) \times C = (A \times C) \cup (B \times C)$.

\pagebreak
# Section 3.4 (p227)

## 16. Exercise 1.d

$$(p + p'q)' = p'q'$$

## 17. Exercise 2.f

$$(ab) \cdot (bc)' = (ab) \cdot c'$$

## 18. Exercise 6.b

$$
\begin{aligned}
  a' + b &= (ab)' + b     &\text{Substituting }ab = a \\
         &= (a' + b') + b &\text{De Morgan's} \\
         &= a' + (b' + b) &\text{Associative} \\
         &= a' + 1        &\text{Negation} \\
         &= 1             &\text{Universal Bound}
\end{aligned}
$$

## 19. Exercise 14

$$
\begin{aligned}
  ab + (a' + b') &= (ab + a') + b'        &\text{Associative} \\
                 &= (a' + ab) + b'        &\text{Commutative} \\
                 &= (a' + a)(a' + b) + b' &\text{Distributive} \\
                 &= (a + a')(a' + b) + b' &\text{Commutative} \\
                 &= 1 \cdot (a' + b) + b' &\text{Negation} \\
                 &= (a' + b) \cdot 1 + b' &\text{Commutative} \\
                 &= (a' + b) + b'         &\text{Identity} \\
                 &= a' + (b + b')         &\text{Associative} \\
                 &= a' + 1                &\text{Negation} \\
                 &= 1                     &\text{Universal Bound} \\
\end{aligned}
$$

$$
\begin{aligned}
  ab \cdot (a' + b') &= (ab) \cdot a' + (ab) \cdot b' &\text{Distributive} \\
                     &= a' \cdot (ab) + (ab) \cdot b' &\text{Commutative} \\
                     &= (a'a) \cdot b + (ab) \cdot b' &\text{Associative} \\
                     &= (aa') \cdot b + (ab) \cdot b' &\text{Commutative} \\
                     &= 0 \cdot b + (ab) \cdot b'     &\text{Negation} \\
                     &= b \cdot 0 + (ab) \cdot b'     &\text{Commutative} \\
                     &= 0 + (ab) \cdot b'             &\text{Universal Bound} \\
                     &= 0 + a \cdot (bb')             &\text{Associative} \\
                     &= 0 + a \cdot 0                 &\text{Negation} \\
                     &= 0 + 0                         &\text{Universal Bound} \\
                     &= 0                             &\text{Idempotent}
\end{aligned}
$$

