---
title: "Assignment 1"
author: "Qianlang Chen"
date: "Mon 01/13/2020"

output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section 1.2

### Exercise 1.m (p21)

The next term in the sequence is 18, according to how the elements in the sequence appear to be positive multiples of 3 in order. This feature can be described with the following closed formula:

$$a_n=3n$$

The above closed formula can also be rewritten as a recursive formula:

\begin{align*}
a_1&=3\\
a_n&=a_{n-1}+3
\end{align*}

### Exercise 7.g (p21)

The first five terms:

\begin{align*}
a_1&=2^{2\times 1-1}-1=1\\
a_2&=2^{2\times 2-1}-1=7\\
a_3&=2^{2\times 3-1}-1=31\\
a_4&=2^{2\times 4-1}-1=127\\
a_5&=2^{2\times 5-1}-1=511
\end{align*}

Recursive formula:

\begin{align*}
a_1&=1\\
a_n&=4\times a_{n-1}+3
\end{align*}

\pagebreak <!-- temporary -->
### Exercise 9.a (p21)

The first five terms:

\begin{align*}
a_1&=5\\
a_2&=a_{2-1}+(2+4)=11\\
a_3&=a_{3-1}+(3+4)=18\\
a_4&=a_{4-1}+(4+4)=26\\
a_5&=a_{5-1}+(5+4)=35
\end{align*}

Closed formula:

$$a_n=\frac{n^2+n}{2}+4n$$

### Exercise 30 (p23)

**Part (a)**

* $a_1=A$

* $a_2=a_{2/2}B=a_1B=AB$

* $a_3=a_{(3-1)/2}A=a_1A=AA$

* $a_4=a_{4/2}B=a_2B=ABB$

* $a_5=a_{(5-1)/2}A=a_2A=ABA$

* $a_6=a_{6/2}B=a_3B=AAB$

* $a_7=a_{(7-1)/2}A=a_3A=AAA$

* $a_8=a_{8/2}B=a_4B=ABBB$

* $a_9=a_{(9-1)/2}A=a_4A=ABBA$

* $a_{10}=a_{10/2}B=a_5B=ABAB$

**Part (b)**

* $a_{17}=a_{(17-1)/2}A=a_8A=ABBBA$

* $a_{21}=a_{(21-1)/2}A=a_{10}A=ABABA$

**Part (c)**

* $a_{630}=a_{630/2}B=a_{315}B=ABBAAABAAB$

* $a_{631}=a_{(631-1)/2}A=a_{315}A=ABBAAABAAA$

\pagebreak
# Section 1.3

### Exercise 1.a (p37)

Let $p$ represent "$A$ is telling the truth" and $q$ represent "$B$ is telling the truth," according to the information given by the problem, we can generate the following truth table:

\begin{displaymath}
\begin{array}{|c c|c c|}
p&q&p\land q&\lnot p\\
\hline
T&T&T&F\\
T&F&F&F\\
F&T&F&T\\
F&F&F&T\\
\end{array}
\end{displaymath}

As seen from the truth table, only the third row provides a consistent result (where when $p=F$ and $q=T$, $p=p\land q$ and $q=\lnot p$). Therefore, $A$ is lying, and $B$ is telling the truth.

### Exercise 4.a (p37)

$$\lnot p\land(q\lor r)$$

where $p$, $q$, and $r$ represent $A$, $B$, and $C$ being truthful, respectively.

### Exercise 10.d (p38)

$$(x\leq0)\land(y\leq0)$$

### Exercise 24.b (p40)

\begin{align*}
(p\lor t)\land(p\lor c)&\equiv t\land(p\lor c)&\text{Universal bound}\\
&\equiv t\land p&\text{Identity}\\
&\equiv p\land t&\text{Commutative}\\
&\equiv p&\text{Identity}
\end{align*}

### Problem 7 (Java method)

Since `charIsNotLowerCaseLetter(c)` always produces exactly the opposite result of `charIsLowerCaseLetter(c)` and the definition of `charIsLowerCaseLetter(c)` is `'a' <= c && c <= 'z'`, according to De Morgan's Law,

```
                                !('a' <= c && c <= 'z')
                            === !('a' <= c) || !(c <= 'z')
                            === 'a' > c || c > 'z'
```

\pagebreak
# Section 1.4

### Exercise 14.c (p52)

\begin{align*}
\lnot(\forall x\in\mathbb{Z},\exists y\in\mathbb{R},x=2y)&\equiv\exists x\in\mathbb{Z},\lnot(\exists y\in\mathbb{R},x=2y)\\
&\equiv\exists x\in\mathbb{Z},\forall y\in\mathbb{R},\lnot(x=2y)\\
&\equiv\exists x\in\mathbb{Z},\forall y\in\mathbb{R},x\neq 2y
\end{align*}

### Exercise 15.c (p52)

The original statement is true:
$$\forall x\in\mathbb{Z},\exists y\in\mathbb{R},x=2y$$

### Exercise 17.c (p52)

There exists a positive integer $x$, which for every positive integer $y$, $y$ is greater than or equal to $x$, or $y$ is not a factor of $x$.

### Exercise 20.b (p52)

The negation of the original statement is true: "there exist two real numbers $x$ and $y$, which for every integer $n$, $x\geq n$ or $n\geq y$."

\pagebreak
# Section 1.5

### Exercise 11.c (p66)

This statement is true for elements in $D$.

### Exercise 11.e (p66)

This statement is true for elements in $D$.

### Exercise 14.d (p67)

$$\forall x\in\mathbb{R^+},x<\sqrt{2}\rightarrow \frac{2}{x}>\sqrt2$$

### Exercise 17.a (p67)

$$n\bmod{5}=0\rightarrow(n\bmod{10}=5)\lor(n\bmod{10}=0)$$

### Exercise 25.e (p67)

If a triangle is not an isosceles triangle, then it has neither two equal sides nor two equal angles.

### Exercise 26.e (p67)

If a triangle is an isosceles triangle, then it has either two equal sides or two equal angles.

### Exercise 27.e (p67)

If a triangle has neither two equal sides nor two equal angles, then it is not an isosceles triangle.

