
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'z\xca\xccV\xcd\xd9\x8d\xc5D]-\xe4xvq\x86'
    
_lr_action_items = {'LPAREN':([0,2,3,4,5,6,7,8,9,11,12,],[4,4,-4,4,-7,-8,4,-3,-5,4,-6,]),'EPS':([0,2,3,4,5,6,7,8,9,11,12,],[5,5,-4,5,-7,-8,5,-3,-5,5,-6,]),'STR':([0,2,3,4,5,6,7,8,9,11,12,],[6,6,-4,6,-7,-8,6,-3,-5,6,-6,]),'$end':([1,2,3,5,6,8,9,11,12,],[0,-2,-4,-7,-8,-3,-5,-1,-6,]),'PLUS':([1,2,3,5,6,8,9,10,11,12,],[7,-2,-4,-7,-8,-3,-5,7,-1,-6,]),'RPAREN':([2,3,5,6,8,9,10,11,12,],[-2,-4,-7,-8,-3,-5,12,-1,-6,]),'STAR':([3,5,6,8,9,12,],[9,-7,-8,9,-5,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,],[1,10,]),'catexp':([0,4,7,],[2,2,11,]),'ordyexp':([0,2,4,7,11,],[3,8,3,3,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS catexp','expression',3,'p_expression_plus','<ipython-input-4-d25c574de024>',30),
  ('expression -> catexp','expression',1,'p_expression_plus1','<ipython-input-4-d25c574de024>',39),
  ('catexp -> catexp ordyexp','catexp',2,'p_expression_cat','<ipython-input-4-d25c574de024>',44),
  ('catexp -> ordyexp','catexp',1,'p_expression_cat1','<ipython-input-4-d25c574de024>',53),
  ('ordyexp -> ordyexp STAR','ordyexp',2,'p_expression_ordy_star','<ipython-input-4-d25c574de024>',62),
  ('ordyexp -> LPAREN expression RPAREN','ordyexp',3,'p_expression_ordy_paren','<ipython-input-4-d25c574de024>',83),
  ('ordyexp -> EPS','ordyexp',1,'p_expression_ordy_eps','<ipython-input-4-d25c574de024>',106),
  ('ordyexp -> STR','ordyexp',1,'p_expression_ordy_str','<ipython-input-4-d25c574de024>',117),
]
